# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 11:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20170621_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='teaser',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
        migrations.AlterField(
            model_name='content',
            name='dateadded',
            field=models.DateTimeField(auto_now_add=True, db_column='dateAdded'),
        ),
        migrations.AlterField(
            model_name='content',
            name='datemodified',
            field=models.DateTimeField(auto_now=True, db_column='dateModified', null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='published',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='content',
            name='view',
            field=models.ForeignKey(blank=True, db_column='view', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Views'),
        ),
    ]
