# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20171218_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='content',
            name='header',
            field=markdownx.models.MarkdownxField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
