# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20171219_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(max_length=4096),
        ),
    ]
