# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_content_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='shortname',
            field=models.CharField(db_column='shortName', max_length=255, unique=True),
        ),
    ]
